/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    categories: Category;
    tags: Tag;
    authors: Author;
    articles: Article;
    videos: Video;
    promos: Promo;
    releases: Release;
    channels: Channel;
    outbox: Outbox;
    'delivery-keys': DeliveryKey;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    promos: PromosSelect<false> | PromosSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    channels: ChannelsSelect<false> | ChannelsSelect<true>;
    outbox: OutboxSelect<false> | OutboxSelect<true>;
    'delivery-keys': DeliveryKeysSelect<false> | DeliveryKeysSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Попадает в URL и в ключ кеша выдачи. После первой публикации не меняется: смена slug — это новый тенант, а не переименование.
   */
  slug: string;
  /**
   * Например https://apex.de. Без него лента RSS и карта сайта не собираются: ссылкам некуда вести.
   */
  publicUrl?: string | null;
  kind: 'brand' | 'region' | 'site';
  /**
   * Пусто только у бренда. Сайт наследуется от региона или напрямую от бренда.
   */
  parent?: (number | null) | Tenant;
  jurisdiction: {
    mode: 'inherit' | 'override' | 'fork';
    /**
     * Определяет обязательные предупреждения, запрещённые продукты и правовой набор. Обязательна для сайта — своя или унаследованная: без неё релиз не собирается.
     */
    value?: string | null;
  };
  availableLocales: {
    mode: 'inherit' | 'extend' | 'fork';
    /**
     * Языки, на которых существует сайт. Наследуются от бренда и региона; «отвязано» означает, что новые локали сверху сюда больше не приезжают.
     */
    items?:
      | {
          code: string;
          id?: string | null;
        }[]
      | null;
  };
  defaultLocale: {
    mode: 'inherit' | 'override' | 'fork';
    /**
     * Обязана входить в перечень разрешённых локалей — с учётом наследования.
     */
    value?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  /**
   * Роль определяет права. Смена роли — событие аудита, а не рядовая правка карточки.
   */
  role: 'brand-admin' | 'site-admin' | 'editor' | 'author' | 'compliance' | 'translator' | 'viewer' | 'developer';
  /**
   * Определяет, какие данные видит человек. Привязка к бренду или региону распространяется на всё поддерево. Пустая привязка означает, что не видно ничего.
   */
  tenants?: (number | Tenant)[] | null;
  /**
   * Отзыв доступа выполняется снятием этого флага: учётные записи не удаляются, иначе теряется история аудита.
   */
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Альтернативный текст обязателен: без него материал не пройдёт сборку релиза. Это требование доступности, а не формальность.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Что изображено — словами. Читается вслух скринридером и показывается, когда картинка не загрузилась.
   */
  alt: string;
  /**
   * Файл бренда доступен всем его сайтам — так же, как категории.
   */
  owner: number | Tenant;
  /**
   * Автор или агентство. Требуется по условиям фотобанков и служит доказательством права на использование.
   */
  credit?: string | null;
  /**
   * Видимая подпись под изображением. В отличие от alt — необязательна.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Раздел, в котором живёт материал. У записи она одна. Категория бренда доступна всем его сайтам.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Попадает в адреса. После публикации менять нельзя — ломаются ссылки.
   */
  slug: string;
  /**
   * Бренд, регион или сайт. Запись доступна владельцу и всему его поддереву: категория бренда видна всем его сайтам.
   */
  owner: number | Tenant;
  /**
   * Используется на странице раздела и в разметке для поисковых систем.
   */
  description?: string | null;
  /**
   * Меньше — выше в списках. Одинаковые значения сортируются по названию.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Сквозная подборка. Тегов у записи может быть много, раздела они не задают.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * Попадает в адреса. После публикации менять нельзя — ломаются ссылки.
   */
  slug: string;
  /**
   * Бренд, регион или сайт. Запись доступна владельцу и всему его поддереву: категория бренда видна всем его сайтам.
   */
  owner: number | Tenant;
  /**
   * Используется на странице раздела и в разметке для поисковых систем.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Карточка автора уходит в разметку страницы. Для финансовой тематики это влияет на ранжирование напрямую.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  title: string;
  /**
   * Попадает в адреса. После публикации менять нельзя — ломаются ссылки.
   */
  slug: string;
  /**
   * Бренд, регион или сайт. Запись доступна владельцу и всему его поддереву: категория бренда видна всем его сайтам.
   */
  owner: number | Tenant;
  /**
   * Например: аналитик рынка облигаций. Общие слова здесь работают против нас.
   */
  role: string;
  /**
   * Опыт и квалификация: чем подтверждается право этого человека писать о рынке.
   */
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Внешние подтверждения личности: LinkedIn, публикации, профиль регулятора.
   */
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Оговорка о том, что материалы не являются инвестиционной рекомендацией. Требуется регулятором и подставляется в материалы автора.
   */
  disclaimer?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Публикуется мгновенно по наступлении даты — сборка релиза не требуется. Снять с витрины можно датой окончания или архивом; удаление оставлено только разработчику.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Попадает в адрес материала. После публикации менять нельзя.
   */
  slug: string;
  /**
   * Материал принадлежит одному сайту. Изоляция тенантов стоит на этом поле.
   */
  site: number | Tenant;
  /**
   * Код из числа объявленных у сайта: en, de, ru. Материал на другом языке — отдельная запись, а не перевод этой.
   */
  locale: string;
  /**
   * Показывается в ленте и в выдаче поисковых систем. Без него лента выглядит пустой.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (number | null) | Media;
  /**
   * Ровно одна: она задаёт раздел и адрес.
   */
  category?: (number | null) | Category;
  tags?: (number | Tag)[] | null;
  authors?: (number | Author)[] | null;
  /**
   * Откуда взят материал, если он не оригинальный.
   */
  source?: string | null;
  /**
   * Состояния «запланировано» здесь нет: это следствие пары «опубликовано + дата в будущем», а не отдельное состояние.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Момент появления на витрине. Дата в будущем означает эмбарго: до неё материал невидим снаружи, даже будучи опубликованным.
   */
  publishAt?: string | null;
  /**
   * Пусто — висит бессрочно. Материал гаснет сам, без чьего-либо участия.
   */
  unpublishAt?: string | null;
  /**
   * Вычисляется из текста при сохранении. Правится только через правку текста.
   */
  readingMinutes?: number | null;
  /**
   * Символы MDS. Терминал показывает материал в карточке инструмента. Символ, которого нет в снапшоте MDS, наружу не отдаётся.
   */
  relatedInstruments?:
    | {
        symbol: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Пусто — материал доступен во всех юрисдикциях сайта. Механизм разграничения появится на M5; поле заполняется уже сейчас.
   */
  jurisdictions?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Держится вверху ленты независимо от даты.
   */
  pinned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Состояние эфира («скоро», «в эфире», «запись») вычисляется из времени и не хранится: ручное поле гарантированно протухнет.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  slug: string;
  /**
   * Материал принадлежит одному сайту. Изоляция тенантов стоит на этом поле.
   */
  site: number | Tenant;
  /**
   * Код из числа объявленных у сайта: en, de, ru. Материал на другом языке — отдельная запись, а не перевод этой.
   */
  locale: string;
  description?: string | null;
  provider: 'youtube' | 'vimeo' | 'self-hosted';
  /**
   * Для YouTube и Vimeo. Для собственного хранилища заполняется файл ниже.
   */
  externalId?: string | null;
  media?: (number | null) | Media;
  poster?: (number | null) | Media;
  /**
   * Пусто — это ролик, а не трансляция: он сразу считается записью. Проставлять фиктивное время ради формы не нужно.
   */
  startsAt?: string | null;
  /**
   * Пусто у начавшегося эфира означает «идёт»: у прямой трансляции время окончания обычно неизвестно заранее.
   */
  endsAt?: string | null;
  speakers?: (number | Author)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Состояния «запланировано» здесь нет: это следствие пары «опубликовано + дата в будущем», а не отдельное состояние.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Момент появления на витрине. Дата в будущем означает эмбарго: до неё материал невидим снаружи, даже будучи опубликованным.
   */
  publishAt?: string | null;
  /**
   * Пусто — висит бессрочно. Материал гаснет сам, без чьего-либо участия.
   */
  unpublishAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Гаснет само по времени окончания — снимать вручную не нужно и не следует: ручное снятие забывают.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos".
 */
export interface Promo {
  id: number;
  title: string;
  slug: string;
  /**
   * Материал принадлежит одному сайту. Изоляция тенантов стоит на этом поле.
   */
  site: number | Tenant;
  /**
   * Код из числа объявленных у сайта: en, de, ru. Материал на другом языке — отдельная запись, а не перевод этой.
   */
  locale: string;
  /**
   * Короткая метка: «Новое», «−50%».
   */
  badge?: string | null;
  description?: string | null;
  /**
   * Обязательны: предложение без условий в регулируемом домене — это нарушение, а не недоработка вёрстки.
   */
  terms: string;
  image?: (number | null) | Media;
  ctaLabel?: string | null;
  /**
   * Внешний адрес только по https: смешанное содержимое ломает страницу.
   */
  ctaHref?: string | null;
  /**
   * Пусто — во всех юрисдикциях сайта. Предложение, недопустимое в юрисдикции, ограничивается здесь.
   */
  jurisdictions?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Больше — выше. При равенстве побеждает более позднее по времени начала.
   */
  priority: number;
  featured?: boolean | null;
  /**
   * Состояния «запланировано» здесь нет: это следствие пары «опубликовано + дата в будущем», а не отдельное состояние.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Момент появления на витрине. Дата в будущем означает эмбарго: до неё материал невидим снаружи, даже будучи опубликованным.
   */
  publishAt?: string | null;
  /**
   * Пусто — висит бессрочно. Материал гаснет сам, без чьего-либо участия.
   */
  unpublishAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Собранный релиз неизменяем: правки после сборки невозможны ни через интерфейс, ни напрямую в базе. Откат выполняется переключением канала.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  siteId: string;
  siteSlug: string;
  /**
   * Свой у каждого сайта, монотонный. Выданный номер не выдаётся повторно — даже если сборка провалилась.
   */
  number: number;
  /**
   * Например, apex-de #42 — то, чем оперируют в переписке.
   */
  label: string;
  /**
   * Правки возможны только пока релиз собирается. После перехода в «готов» или «провален» запись замораживается на уровне базы.
   */
  status: 'building' | 'ready' | 'failed';
  /**
   * Полное состояние структуры сайта на момент сборки.
   */
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Участвует в ETag выдачи; устойчив к порядку полей.
   */
  contentHash?: string | null;
  /**
   * Почему сборка прошла или была отклонена. Хранится и у проваленных релизов — иначе причина отказа теряется.
   */
  validationReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  builtAt?: string | null;
  builtById?: string | null;
  builtByEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Откат — это переключение канала на предыдущий релиз.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels".
 */
export interface Channel {
  id: number;
  siteId: string;
  siteSlug: string;
  name: 'live' | 'staging';
  label: string;
  releaseId?: string | null;
  releaseNumber?: number | null;
  switchedAt?: string | null;
  switchedById?: string | null;
  switchedByEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Недоставленное событие видно здесь и повторяется автоматически. Кнопка повтора сбрасывает время следующей попытки.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox".
 */
export interface Outbox {
  id: number;
  /**
   * На нём стоит идемпотентность потребителя: повторная доставка того же события не должна применяться дважды.
   */
  eventId: string;
  routingKey: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  publishedAt?: string | null;
  attempts: number;
  nextAttemptAt: string;
  lastError?: string | null;
  tenantId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Секрет ключа показывается один раз при выдаче и нигде не хранится. Потерянный ключ не восстанавливается — выпускается новый, старый отзывается.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-keys".
 */
export interface DeliveryKey {
  id: number;
  /**
   * Кто именно ходит этим ключом: сайт, кабинет, терминал.
   */
  name: string;
  /**
   * Открытая часть: по ней находится запись. Секретом не является.
   */
  keyId: string;
  secretHash: string;
  /**
   * Утёкший ключ одного потребителя не должен открывать данные другого — поэтому прав выдаётся ровно столько, сколько нужно.
   */
  scopes: ('delivery:read' | 'preview:read' | 'terminal:read')[];
  /**
   * Пустая привязка означает, что ключ не открывает ничего. Это отказ, а не доступ ко всему.
   */
  sites?: (number | Tenant)[] | null;
  /**
   * Отзыв ключа — снятие этого флага; запись остаётся для аудита.
   */
  isActive: boolean;
  /**
   * Пусто — бессрочно. Для ключей подрядчиков срок стоит задавать всегда.
   */
  expiresAt?: string | null;
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Только добавление. Изменение и удаление записей запрещены и на уровне приложения, и на уровне базы данных.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  occurredAt: string;
  action:
    | 'create'
    | 'update'
    | 'delete'
    | 'login'
    | 'logout'
    | 'login-failed'
    | 'access-denied'
    | 'publish'
    | 'rollback'
    | 'approve';
  targetCollection: string;
  targetId?: string | null;
  tenantId?: string | null;
  tenantSlug?: string | null;
  actorId?: string | null;
  actorEmail?: string | null;
  actorRole?: string | null;
  summary: string;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'promos';
        value: number | Promo;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'channels';
        value: number | Channel;
      } | null)
    | ({
        relationTo: 'outbox';
        value: number | Outbox;
      } | null)
    | ({
        relationTo: 'delivery-keys';
        value: number | DeliveryKey;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  publicUrl?: T;
  kind?: T;
  parent?: T;
  jurisdiction?:
    | T
    | {
        mode?: T;
        value?: T;
      };
  availableLocales?:
    | T
    | {
        mode?: T;
        items?:
          | T
          | {
              code?: T;
              id?: T;
            };
      };
  defaultLocale?:
    | T
    | {
        mode?: T;
        value?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  tenants?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  owner?: T;
  credit?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  owner?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  owner?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  owner?: T;
  role?: T;
  bio?: T;
  photo?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  site?: T;
  locale?: T;
  excerpt?: T;
  body?: T;
  cover?: T;
  category?: T;
  tags?: T;
  authors?: T;
  source?: T;
  status?: T;
  publishAt?: T;
  unpublishAt?: T;
  readingMinutes?: T;
  relatedInstruments?:
    | T
    | {
        symbol?: T;
        id?: T;
      };
  jurisdictions?:
    | T
    | {
        code?: T;
        id?: T;
      };
  featured?: T;
  pinned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  site?: T;
  locale?: T;
  description?: T;
  provider?: T;
  externalId?: T;
  media?: T;
  poster?: T;
  startsAt?: T;
  endsAt?: T;
  speakers?: T;
  tags?: T;
  status?: T;
  publishAt?: T;
  unpublishAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promos_select".
 */
export interface PromosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  site?: T;
  locale?: T;
  badge?: T;
  description?: T;
  terms?: T;
  image?: T;
  ctaLabel?: T;
  ctaHref?: T;
  jurisdictions?:
    | T
    | {
        code?: T;
        id?: T;
      };
  priority?: T;
  featured?: T;
  status?: T;
  publishAt?: T;
  unpublishAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  siteId?: T;
  siteSlug?: T;
  number?: T;
  label?: T;
  status?: T;
  snapshot?: T;
  contentHash?: T;
  validationReport?: T;
  builtAt?: T;
  builtById?: T;
  builtByEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels_select".
 */
export interface ChannelsSelect<T extends boolean = true> {
  siteId?: T;
  siteSlug?: T;
  name?: T;
  label?: T;
  releaseId?: T;
  releaseNumber?: T;
  switchedAt?: T;
  switchedById?: T;
  switchedByEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outbox_select".
 */
export interface OutboxSelect<T extends boolean = true> {
  eventId?: T;
  routingKey?: T;
  payload?: T;
  occurredAt?: T;
  publishedAt?: T;
  attempts?: T;
  nextAttemptAt?: T;
  lastError?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-keys_select".
 */
export interface DeliveryKeysSelect<T extends boolean = true> {
  name?: T;
  keyId?: T;
  secretHash?: T;
  scopes?: T;
  sites?: T;
  isActive?: T;
  expiresAt?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  occurredAt?: T;
  action?: T;
  targetCollection?: T;
  targetId?: T;
  tenantId?: T;
  tenantSlug?: T;
  actorId?: T;
  actorEmail?: T;
  actorRole?: T;
  summary?: T;
  changes?: T;
  requestId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}