/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    releases: Release;
    channels: Channel;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    channels: ChannelsSelect<false> | ChannelsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Попадает в URL и в ключ кеша выдачи. После первой публикации не меняется: смена slug — это новый тенант, а не переименование.
   */
  slug: string;
  kind: 'brand' | 'region' | 'site';
  /**
   * Пусто только у бренда. Сайт наследуется от региона или напрямую от бренда.
   */
  parent?: (number | null) | Tenant;
  jurisdiction: {
    mode: 'inherit' | 'override' | 'fork';
    /**
     * Определяет обязательные предупреждения, запрещённые продукты и правовой набор. Обязательна для сайта — своя или унаследованная: без неё релиз не собирается.
     */
    value?: string | null;
  };
  availableLocales: {
    mode: 'inherit' | 'extend' | 'fork';
    /**
     * Языки, на которых существует сайт. Наследуются от бренда и региона; «отвязано» означает, что новые локали сверху сюда больше не приезжают.
     */
    items?:
      | {
          code: string;
          id?: string | null;
        }[]
      | null;
  };
  defaultLocale: {
    mode: 'inherit' | 'override' | 'fork';
    /**
     * Обязана входить в перечень разрешённых локалей — с учётом наследования.
     */
    value?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  /**
   * Роль определяет права. Смена роли — событие аудита, а не рядовая правка карточки.
   */
  role: 'brand-admin' | 'site-admin' | 'editor' | 'author' | 'compliance' | 'translator' | 'viewer' | 'developer';
  /**
   * Определяет, какие данные видит человек. Привязка к бренду или региону распространяется на всё поддерево. Пустая привязка означает, что не видно ничего.
   */
  tenants?: (number | Tenant)[] | null;
  /**
   * Отзыв доступа выполняется снятием этого флага: учётные записи не удаляются, иначе теряется история аудита.
   */
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Собранный релиз неизменяем: правки после сборки невозможны ни через интерфейс, ни напрямую в базе. Откат выполняется переключением канала.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  siteId: string;
  siteSlug: string;
  /**
   * Свой у каждого сайта, монотонный. Выданный номер не выдаётся повторно — даже если сборка провалилась.
   */
  number: number;
  /**
   * Например, apex-de #42 — то, чем оперируют в переписке.
   */
  label: string;
  /**
   * Правки возможны только пока релиз собирается. После перехода в «готов» или «провален» запись замораживается на уровне базы.
   */
  status: 'building' | 'ready' | 'failed';
  /**
   * Полное состояние структуры сайта на момент сборки.
   */
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Участвует в ETag выдачи; устойчив к порядку полей.
   */
  contentHash?: string | null;
  /**
   * Почему сборка прошла или была отклонена. Хранится и у проваленных релизов — иначе причина отказа теряется.
   */
  validationReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  builtAt?: string | null;
  builtById?: string | null;
  builtByEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Откат — это переключение канала на предыдущий релиз.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels".
 */
export interface Channel {
  id: number;
  siteId: string;
  siteSlug: string;
  name: 'live' | 'staging';
  label: string;
  releaseId?: string | null;
  releaseNumber?: number | null;
  switchedAt?: string | null;
  switchedById?: string | null;
  switchedByEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Только добавление. Изменение и удаление записей запрещены и на уровне приложения, и на уровне базы данных.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  occurredAt: string;
  action:
    'create' | 'update' | 'delete' | 'login' | 'login-failed' | 'access-denied' | 'publish' | 'rollback' | 'approve';
  targetCollection: string;
  targetId?: string | null;
  tenantId?: string | null;
  tenantSlug?: string | null;
  actorId?: string | null;
  actorEmail?: string | null;
  actorRole?: string | null;
  summary: string;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'channels';
        value: number | Channel;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  parent?: T;
  jurisdiction?:
    | T
    | {
        mode?: T;
        value?: T;
      };
  availableLocales?:
    | T
    | {
        mode?: T;
        items?:
          | T
          | {
              code?: T;
              id?: T;
            };
      };
  defaultLocale?:
    | T
    | {
        mode?: T;
        value?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  tenants?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  siteId?: T;
  siteSlug?: T;
  number?: T;
  label?: T;
  status?: T;
  snapshot?: T;
  contentHash?: T;
  validationReport?: T;
  builtAt?: T;
  builtById?: T;
  builtByEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels_select".
 */
export interface ChannelsSelect<T extends boolean = true> {
  siteId?: T;
  siteSlug?: T;
  name?: T;
  label?: T;
  releaseId?: T;
  releaseNumber?: T;
  switchedAt?: T;
  switchedById?: T;
  switchedByEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  occurredAt?: T;
  action?: T;
  targetCollection?: T;
  targetId?: T;
  tenantId?: T;
  tenantSlug?: T;
  actorId?: T;
  actorEmail?: T;
  actorRole?: T;
  summary?: T;
  changes?: T;
  requestId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}